### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by skariel**
@theindiepocalypse hi/
@theindiepocalypse list admins/

### CODE REVIEW

**Comment by theindiepocalypse** [comment]
@skariel Thanks for opening this pull request!hi!

 @theindiepocalypse you @skariel  are admins

**Comment by skariel** [comment]
@theindiepocalypse hi

**Comment by theindiepocalypse** [comment]
@skariel hi!

**Comment by theindiepocalypse** [comment]
PR updated, all offers cleared!
please plase your new offers

**Comment by theindiepocalypse** [comment]
@skariel hi!

 @theindiepocalypse you @skariel  are admins

**Comment by skariel** [comment]
@theindiepocalypse hi

**Comment by theindiepocalypse** [comment]
@skariel hi!

**Comment by theindiepocalypse** [comment]
PR updated, all offers cleared!
please place your new offers

**Comment by skariel** [comment]
@theindiepocalypse list offers

**Comment by theindiepocalypse** [comment]
@skariel such command... much help please

**Comment by skariel** [comment]
@theindiepocalypse list owners

**Comment by theindiepocalypse** [comment]
@skariel 

Owner | Percent
-------|---------
*total* | 100.0

**Comment by skariel** [comment]
@theindiepocalypse list admins

**Comment by theindiepocalypse** [comment]
@skariel  @theindiepocalypse and you, are admins

**Comment by theindiepocalypse** [comment]
PR updated, all offers cleared!
please place your new offers

**Comment by skariel** [comment]
@theindiepocalypse merge with this comment

**Comment by theindiepocalypse** [comment]
@skariel: this pull request is not mergeable automatically (the merge button) maybe a rebase will solve the issue? I can only merge with the merge button...

**Comment by skariel** [comment]
@theindiepocalypse merge with this comment

**Comment by theindiepocalypse** [comment]
@skariel: this pull request is not mergeable automatically (the merge button) maybe a rebase will solve the issue? I can only merge with the merge button...

**Comment by skariel** [comment]
@theindiepocalypse close

**Comment by theindiepocalypse** [comment]
@skariel: such command... much help please

**Pull request closed without merging**
